#!/usr/bin/env bash
#configures an Ubuntu server

sudo sed -i '/localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8   facebook.com" | sudo tee -a /etc/hosts > /dev/null